---
# tasks file for roles/mysql
- name: include  install_repo.yml
  include: install_repo.yml

- name: include mysql_server.yml when mysql_install_type == 'server'
  include: mysql_server.yml
  when: mysql_install_type == 'server'

- name: include install_client.yml when mysql_install_type == 'client'
  include: install_client.yml
  when: mysql_install_type == "client"
