---
- name: include install_server.yml
  include: install_server.yml

- name: include configure.yml
  include: configure.yml

- name: include service.yml
  include: service.yml
# 如果是第一次启动mysql, 则进行安全化配置

- name: include init_secure.yml when first install mysql server
  include: init_secure.yml
  when: mysql_install_result.changed or mysql_first_install

- name: include create_db.yml
  include: create_db.yml
